url: http://gertclaus.github.io/fedpol-portfolio/
#baseurl: http://gertclaus.github.io/fedpol-portfolio/
baseurl: 

# Site settings
title: CGC Digital
email: cgc.digital@police.belgium.eu
description: "Portfolio website of the former Webteam"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F04E1D
  secondary: 343434  
  secondary-dark: BFB591

# Team names, titles and social links
people:
- name: Gert Claus
  pic: 1
  position: Web Designer & Social Media Consultant
  social:
    - title: twitter
      url: https://twitter.com/GertCls
    - title: facebook
      url: https://www.facebook.com/gert.claus
    - title: github
      url: https://github.com/GertClaus
      
- name: Laurent Bianchin
  pic: 2
  position: Web Developer & Javascript specialist
  social:
    - title: twitter
      url: https://twitter.com/Shiro1981
    - title: facebook
      url: https://www.facebook.com/laurent.bianchin?fref=ts
    - title: github
      url: https://github.com/lbianchin
      
- name: Pascal Niego
  pic: 3
  position: Web Developer & PHP specialist
  social:
    - title: twitter
      url: https://twitter.com/Darthsidious30
    - title: facebook
      url: https://www.facebook.com/darthsidious30?fref=ts
    - title: github
      url: https://github.com/darthsidious30
      
- name: Claudine Van Grieken
  pic: 4
  position: Team leader & professional debugger
  social:
    - title: twitter
      url: https://twitter.com/ClaudineVG
    - title: facebook
      url: https://www.facebook.com/claudine.vangrieken?fref=ts
    - title: github
      url: https://github.com/clovangrieken


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fedpol_pers
  - title: facebook
    url: https://www.facebook.com/gert.claus
  - title: instagram
    url: https://www.instagram.com/federalepolitie/
  - title: github
    url: https://github.com/orgs/fedpolbelgium/dashboard

# Postal address (add as many lines as necessary)
address:
  - line: Moleken 36
  - line: B-9260 Wichelen

# Build settings
markdown: kramdown
permalink: pretty